### ISSUE TITLE
Проблемы сборки

### ISSUE THREAD

**Issue by avasyukov** [fopdf/Matrix-and-vector-3d#3]
Оно перестало компилироваться. Вероятно, при попытке привести всё в нужный вид некоторые нужные части были утеряны. Масштаб потерь не очень велик.

На правах наводки примерные места проблем:
- операторов `std::istream& operator>>(istream& mean, Vector3D& v)` стало две копии
- у оператора `std::ostream& operator<<(ostream& wh, const Vector3D& v)` не сходится сигнатура в .h и в .cpp
- не хватает оператора, чтобы выполнилось `cout << "2 * B = " << 2 * B << endl;`
- не хватает оператора, чтобы выполнилось `cout << "D * B = " << D * B << endl;`

**Comment by fopdf** [comment]
Здравствуйте! Перелопатил и пофиксил нужные места.Теперь вроде все работает.
https://github.com/fopdf/Matrix-and-vector-3d
С уважением, Рогов Роман ФАКИ 1 курс

пт, 8 мая 2020 г. в 14:28, Alexey Vasyukov <notifications@github.com>:

**Comment by avasyukov** [comment]
Подтверждаю, решено.
